### PR TITLE
ON WRONG BRANCH - ignore me: support clone of custom Tree

### PR DESCRIPTION
**Pull request by pvojtechovsky**
Hi!

I would like to have own implementation of `com.github.gumtreediff.tree.Tree`. It was no problem to extend Tree and create it using my own TreeContext. Super!

But it is not possible to deepCopy MyTree, because constructor is private.

Thank you
Pavel

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
Is anybody out there? ;-)

**Comment by pvojtechovsky** [comment]
I cannot imagine how might my change cause problem of CI ... any idea why it fails?

**Comment by jrfaller** [comment]
I will check if I can understand the problem!

**Comment by pvojtechovsky** [comment]
Thank you. May be we just have to run CI again?

**Comment by jrfaller** [comment]
OK I understand the problem : the merge is on master instead of develop ;) can you make the PR to targets the develop branch?

Thank you!

**Pull request closed without merging**
