### PR TITLE
Diff class support for Resources

### PR DESCRIPTION
**Pull request by rpau**
This commit is adding a new compute method to support the diff processing of resources instead of paths.

This functionality is intersting when the files that need to be computed are not in the local file and are downloaded from the Internet using APIs in memory.

### CODE REVIEW

**Comment by jrfaller** [comment]
Hi and thanks a lot for the PR!

It seems that there are a couple of formatting issues, but otherwise seems good!

Can you fix the formatting issues?

Cheers!

**Comment by rpau** [comment]
@jrfaller I have no issues updating the code for formatting issues, but looks to me a consequence of the review mode and not a real problem. If you change the diff view to use "unified" you will see that there is nothing impacting the file formatting.
 
Captura de Pantalla 2022-09-13 a las 12 05 54

**Comment by rpau** [comment]
Sure, Now I'll review the issues reported during the build. Sorry for that.

**Comment by rpau** [comment]
@jrfaller Can you merge it now? :)

**Pull request merged**
