### PR TITLE
feat: add command to dump vanilla diff output

### PR DESCRIPTION
**Pull request by algomaster99**
These changes add a command called `htmldiff` which dumps HTML output of vanilla-diff in `stdout`. The dependent CSS and JS are read and then dumped directly into this output. However, two changes must be done before it is ready for merge:
- [x] Make the file path [here](https://github.com/GumTreeDiff/gumtree/compare/develop...algomaster99:htmldiff?expand=1#diff-c44792f1885cb1fdb6cedddb6e14af31c3ce5e027ed465870915aa62735a84e7R149) relative.
- [x] The output doesn't pop this menu when "Legends" is clicked
Screenshot from 2020-11-29 13-31-20

### CODE REVIEW

**Comment by monperrus** [comment]
Thanks for PR!

**Comment by algomaster99** [comment]
@monperrus I needed help with something in these changes. How can I input a path (relative to project) in Java so that I can read its content? Currently, I have to rely on absolute path which is not a good idea.

**Comment by jrfaller** [comment]
Hi @algomaster99 and thanks for the PR!

Maybe you could read the file content using the classloader (https://stackoverflow.com/questions/15749192/how-do-i-load-a-file-from-resource-folder)?

Cheers!

**Comment by algomaster99** [comment]
@monperrus @jrfaller I added an option to dump the output to a file as well.

**Comment by jrfaller** [comment]
Hi and thanks a lot for the PR! I think this is OK 👍

**Pull request merged**
